# Generated by Django 4.0.5 on 2022-06-04 05:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gramApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='uploadDate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
