# Generated by Django 4.0.5 on 2022-06-04 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gramApp', '0002_alter_image_uploaddate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='users',
            new_name='author',
        ),
    ]
