# Generated by Django 4.0.5 on 2022-06-04 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gramApp', '0003_rename_users_image_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='uploads/feed/'),
        ),
    ]
