# Generated by Django 4.0.5 on 2022-06-06 14:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gramApp', '0009_image_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='dislikes',
            field=models.ManyToManyField(blank=True, related_name='dislikes', to=settings.AUTH_USER_MODEL),
        ),
    ]
